export { createAutoscrollMachine } from './autoscroll'
export type { AutoscrollMachine, AutoscrollState } from './autoscroll'
export { computePrependCompensation } from './prepend-compensation'
export type { PrependCompensation } from './prepend-compensation'
export { computeScrollMetrics } from './scroll-metrics'
export type { ScrollMetrics, ScrollReading } from './scroll-metrics'
