<script lang="ts">
  import { debug } from '$lib/stores/debug.svelte'
  import { ui } from '$lib/stores/ui.svelte'
  import { story } from '$lib/stores/story.svelte'
  import { settings } from '$lib/stores/settings.svelte'
  import Sidebar from './Sidebar.svelte'
  import StoryNavPanel from './StoryNavPanel.svelte'
  import Header from './Header.svelte'
  import ProfileWarningBanner from './ProfileWarningBanner.svelte'
  import StoryView from '$lib/components/story/StoryView.svelte'
  import LibraryView from '$lib/components/story/LibraryView.svelte'
  import GalleryTab from '$lib/components/story/GalleryTab.svelte'
  import LorebookView from '$lib/components/lorebook/LorebookView.svelte'
  import MemoryView from '$lib/components/memory/MemoryView.svelte'
  import VaultPanel from '$lib/components/vault/VaultPanel.svelte'
  import SettingsModal from '$lib/components/settings/SettingsModal.svelte'
  import LorebookDebugPanel from '$lib/components/debug/LorebookDebugPanel.svelte'
  import DebugLogModal from '$lib/components/debug/DebugLogModal.svelte'
  import SyncModal from '$lib/components/sync/SyncModal.svelte'
  import STChatImportModal from '$lib/components/modals/STChatImportModal.svelte'
  import UpdateDialog from '$lib/components/updater/UpdateDialog.svelte'
  import { swipe } from '$lib/utils/swipe'
  import { releaseOrphanScrollLock } from '$lib/utils/scrollLock'
  import { createLogger } from '$lib/log'
  import { Bug } from '@lucide/svelte'
  import {
    MIN_SIDEBAR_WIDTH,
    MAX_SIDEBAR_WIDTH,
    MAX_SIDEBAR_RATIO,
    MODAL_CLOSE_TRANSITION_MS,
  } from '$lib/constants/layout'
  import type { Snippet } from 'svelte'

  let { children }: { children?: Snippet } = $props()

  const log = createLogger('AppShell')

  function handleEdgeSwipeLeft() {
    if (story.currentStory && !ui.sidebarOpen) {
      ui.toggleSidebar()
    }
  }

  // Debug button drag state
  let debugBtnX = $state<number | null>(null) // null = use CSS default position
  let debugBtnY = $state<number | null>(null)
  let isDraggingDebug = $state(false)
  let dragStartX = 0
  let dragStartY = 0
  let dragStartBtnX = 0
  let dragStartBtnY = 0
  let dragMoved = false // tracks if pointer moved enough to be a drag
  let suppressNextClickFromPointer = false
  let suppressPointerClickResetTimeout: ReturnType<typeof setTimeout> | null = null
  const DRAG_THRESHOLD = 5 // px before it counts as drag, not click
  const DEBUG_BUTTON_SIZE = 48 // h-12 w-12 = 3rem = 48px

  function clampDebugButtonToViewport() {
    if (debugBtnX === null || debugBtnY === null) return

    debugBtnX = Math.max(0, Math.min(window.innerWidth - DEBUG_BUTTON_SIZE, debugBtnX))
    debugBtnY = Math.max(0, Math.min(window.innerHeight - DEBUG_BUTTON_SIZE, debugBtnY))
  }

  function handleDebugPointerDown(e: PointerEvent) {
    isDraggingDebug = true
    dragMoved = false
    const btn = e.currentTarget as HTMLElement
    btn.setPointerCapture(e.pointerId)

    // If position is null (default), initialize from current computed position
    if (debugBtnX === null || debugBtnY === null) {
      const rect = btn.getBoundingClientRect()
      debugBtnX = rect.left
      debugBtnY = rect.top
    }

    dragStartX = e.clientX
    dragStartY = e.clientY
    dragStartBtnX = debugBtnX
    dragStartBtnY = debugBtnY
    e.preventDefault()
  }

  function handleDebugPointerMove(e: PointerEvent) {
    if (!isDraggingDebug) return

    const dx = e.clientX - dragStartX
    const dy = e.clientY - dragStartY

    if (!dragMoved && Math.abs(dx) < DRAG_THRESHOLD && Math.abs(dy) < DRAG_THRESHOLD) {
      return // below threshold, don't move yet
    }
    dragMoved = true

    // Clamp to viewport
    debugBtnX = Math.max(0, Math.min(window.innerWidth - DEBUG_BUTTON_SIZE, dragStartBtnX + dx))
    debugBtnY = Math.max(0, Math.min(window.innerHeight - DEBUG_BUTTON_SIZE, dragStartBtnY + dy))
  }

  function handleDebugPointerUp() {
    isDraggingDebug = false

    if (dragMoved) {
      // Suppress the click event generated by this pointer interaction.
      suppressNextClickFromPointer = true
      if (suppressPointerClickResetTimeout !== null) {
        clearTimeout(suppressPointerClickResetTimeout)
      }
      suppressPointerClickResetTimeout = setTimeout(() => {
        suppressNextClickFromPointer = false
        suppressPointerClickResetTimeout = null
      }, 0)
    }
  }

  function handleDebugClick() {
    if (suppressNextClickFromPointer) return
    debug.toggleDebugModal()
  }

  function handleWindowResize() {
    clampDebugButtonToViewport()
  }

  // Resizing logic — two panels, one drag at a time
  let resizing = $state<'sidebar' | 'navPanel' | null>(null)
  const isResizing = $derived(resizing !== null)
  let navPanelEl = $state<HTMLDivElement | null>(null)

  function startResizing(target: 'sidebar' | 'navPanel', e: MouseEvent) {
    resizing = target
    e.preventDefault()
  }

  function stopResizing() {
    if (!resizing) return
    const target = resizing
    resizing = null
    // Persist the final width to the database now that resizing is complete.
    if (target === 'sidebar') {
      settings.setSidebarWidth(settings.uiSettings.sidebarWidth)
    } else {
      settings.setNavPanelWidth(settings.uiSettings.navPanelWidth)
    }
  }

  function handleMouseMove(e: MouseEvent) {
    if (!resizing) return

    // The sidebar is flush to the right edge; the nav panel starts wherever the content
    // area does, which is not the window edge once a safe-area inset is in play.
    const newWidth =
      resizing === 'sidebar'
        ? window.innerWidth - e.clientX
        : e.clientX - (navPanelEl?.getBoundingClientRect().left ?? 0)

    // Constraints
    if (
      newWidth >= MIN_SIDEBAR_WIDTH &&
      newWidth <= Math.min(MAX_SIDEBAR_WIDTH, window.innerWidth * MAX_SIDEBAR_RATIO)
    ) {
      // For performance, update the reactive state directly without saving to the database on every mouse movement.
      if (resizing === 'sidebar') {
        settings.uiSettings.sidebarWidth = newWidth
      } else {
        settings.uiSettings.navPanelWidth = newWidth
      }
    }
  }

  // Global cursor and selection handling while resizing
  $effect(() => {
    if (typeof document === 'undefined') return
    if (isResizing) {
      document.body.style.cursor = 'col-resize'
      document.body.style.userSelect = 'none'
    } else {
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
    }
  })

  /**
   * The single owner of orphaned-scroll-lock recovery, for the whole app: watches
   * `document.body` for a lock and, once the close transition has had time to run, releases
   * it if nothing on screen should be holding it. See `$lib/utils/scrollLock`.
   */
  $effect(() => {
    if (typeof document === 'undefined') return

    let settleTimer: ReturnType<typeof setTimeout> | null = null

    const observer = new MutationObserver(() => {
      const { pointerEvents, overflow } = document.body.style
      if (pointerEvents !== 'none' && overflow !== 'hidden') return

      if (settleTimer) clearTimeout(settleTimer)
      settleTimer = setTimeout(() => {
        settleTimer = null
        if (releaseOrphanScrollLock()) log('Released an orphaned body scroll lock')
      }, MODAL_CLOSE_TRANSITION_MS)
    })

    observer.observe(document.body, { attributes: true, attributeFilter: ['style'] })

    return () => {
      if (settleTimer) clearTimeout(settleTimer)
      observer.disconnect()
    }
  })
</script>

<svelte:window
  onmousemove={handleMouseMove}
  onmouseup={stopResizing}
  onmouseleave={stopResizing}
  onresize={handleWindowResize}
/>

<div class="app-shell bg-surface-900 relative flex h-screen w-screen flex-col">
  <!-- Profile Warning Banner (shown when API profiles need updating) -->
  <ProfileWarningBanner />

  <!-- Main app container -->
  <div class="flex min-h-0 flex-1">
    <!-- Mobile sidebar overlay (tap to close) -->
    {#if ui.sidebarOpen && story.currentStory}
      <button
        class="mobile-sidebar-overlay"
        onclick={() => ui.toggleSidebar()}
        aria-label="Close sidebar"
      ></button>
    {/if}

    <!-- Right edge swipe zone for opening sidebar (when closed) -->
    {#if !ui.sidebarOpen && story.currentStory}
      <div
        class="swipe-edge-zone"
        use:swipe={{ onSwipeLeft: handleEdgeSwipeLeft, threshold: 30 }}
      ></div>
    {/if}

    <!-- Left edge swipe zone for opening the nav panel — a region-owning gesture, the mirror
         of the right-edge zone above. Mounted only while neither panel is open, so a
         right-swipe that belongs to the sidebar's tab strip or to dismissing a panel cannot
         also open this one. -->
    {#if !ui.sidebarOpen && !ui.navPanelOpen && story.currentStory}
      <div
        class="swipe-edge-zone swipe-edge-zone-left"
        use:swipe={{ onSwipeRight: () => ui.toggleNavPanel(), threshold: 30 }}
      ></div>
    {/if}

    <!-- Main content area -->
    <div class="flex flex-1 flex-col overflow-hidden">
      <Header />

      <!-- The navigation panel is a flex sibling of the content, so on desktop it pushes.
           `relative` is for the mobile case, where it overlays this area instead — below
           the header, so the control that opened it stays reachable. -->
      <div class="relative flex min-h-0 flex-1">
        {#if ui.navPanelOpen && story.currentStory}
          <button
            class="nav-panel-scrim"
            onclick={() => ui.closeNavPanel()}
            aria-label="Close story navigation"
          ></button>
          <div
            bind:this={navPanelEl}
            class="nav-panel-container relative flex"
            style:width="{settings.uiSettings.navPanelWidth}px"
          >
            <StoryNavPanel />
            <!-- Desktop only: on mobile the panel overlays at a fixed width, so there is
                 nothing to resize. -->
            <button
              type="button"
              class="resizer-handle nav-panel-resizer h-full"
              onmousedown={(e) => startResizing('navPanel', e)}
              aria-label="Story Navigation Resizer"
            ></button>
          </div>
        {/if}

        <main class="min-w-0 flex-1 overflow-hidden">
          {#if ui.activePanel === 'story' && story.currentStory}
            <StoryView />
          {:else if ui.activePanel === 'gallery' && story.currentStory}
            <GalleryTab />
          {:else if ui.activePanel === 'lorebook' && story.currentStory}
            <LorebookView />
          {:else if ui.activePanel === 'memory' && story.currentStory}
            <MemoryView />
          {:else if ui.activePanel === 'vault'}
            <VaultPanel />
          {:else if ui.activePanel === 'library' || !story.currentStory}
            <LibraryView />
          {:else if children}
            {@render children()}
          {/if}
        </main>
      </div>
    </div>

    <!-- Sidebar (Right aligned) -->
    {#if ui.sidebarOpen && story.currentStory}
      <div class="sidebar-container relative flex">
        <!-- Resizer Handle (Desktop only) -->
        <button
          type="button"
          class="resizer-handle hidden h-full sm:block"
          onmousedown={(e) => startResizing('sidebar', e)}
          aria-label="Sidebar Resizer"
        ></button>
        <Sidebar />
      </div>
    {/if}
  </div>

  <!-- Settings Modal -->
  {#if ui.settingsModalOpen}
    <SettingsModal />
  {/if}

  <!-- Lorebook Debug Panel -->
  <LorebookDebugPanel />

  <!-- Debug Log Modal -->
  <DebugLogModal />

  <!-- Sync Modal -->
  <SyncModal />

  <!-- SillyTavern Chat Import Modal -->
  <STChatImportModal />

  <!-- Update Dialog (raised by the startup check and by the Settings button alike) -->
  <UpdateDialog />

  <!-- Floating Debug Button (when debug mode enabled) - draggable, high z-index -->
  {#if settings.uiSettings.debugMode}
    <button
      class="fixed z-30 flex h-12 w-12 items-center justify-center rounded-full bg-amber-600 text-white shadow-lg transition-shadow hover:bg-amber-500 active:shadow-xl"
      class:hidden={debug.debugModalOpen}
      class:cursor-grabbing={isDraggingDebug}
      class:cursor-grab={!isDraggingDebug}
      style="{debugBtnX !== null && debugBtnY !== null
        ? `left: ${debugBtnX}px; top: ${debugBtnY}px;`
        : 'right: 1rem; bottom: 1rem;'} touch-action: none;"
      style:transition={isDraggingDebug ? 'none' : undefined}
      onpointerdown={handleDebugPointerDown}
      onpointermove={handleDebugPointerMove}
      onpointerup={handleDebugPointerUp}
      onclick={handleDebugClick}
      onpointercancel={() => {
        isDraggingDebug = false
      }}
      title="View API Debug Logs (drag to move)"
    >
      <Bug class="pointer-events-none h-5 w-5" />
      {#if debug.requestCount > 0}
        <span
          class="pointer-events-none absolute -top-1 -right-1 flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-xs font-medium"
        >
          {debug.requestCount > 99 ? '99+' : debug.requestCount}
        </span>
      {/if}
    </button>
  {/if}
</div>

<style>
  /*
   * Safe Area Handling — see :root rule in app.css for the --safe-* definitions.
   */

  .app-shell {
    padding-top: var(--safe-top);
    padding-bottom: var(--safe-bottom);
    padding-left: var(--safe-left);
    padding-right: var(--safe-right);
  }

  /* Top safe area background filler - matches header color (bg-surface-800) */
  .app-shell::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: var(--safe-top);
    background-color: var(--color-surface-800);
    z-index: 0;
  }

  /* Bottom safe area background filler - matches main view background */
  .app-shell::after {
    content: '';
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: var(--safe-bottom);
    background-color: var(--color-surface-900);
    z-index: 9999;
    pointer-events: none;
  }

  /* Mobile sidebar overlay - visible only on touch devices */
  .mobile-sidebar-overlay {
    display: none;
    position: fixed;
    inset: 0;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 40;
    border: none;
    cursor: pointer;
  }

  /* Sidebar container for mobile positioning */
  .sidebar-container {
    z-index: 50;
    flex-shrink: 0;
  }

  .resizer-handle {
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    width: 4px;
    cursor: col-resize;
    z-index: 60;
    transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1);
    background-color: transparent;
    border: none;
    padding: 0;
    outline: none;
  }

  .resizer-handle:hover,
  .resizer-handle:focus-visible {
    background-color: var(--color-primary-500, #3b82f6);
    opacity: 0.5;
  }

  .resizer-handle:focus-visible {
    outline: 2px solid var(--color-primary-500, #3b82f6);
    outline-offset: -2px;
  }

  /* Story navigation panel — in flow on desktop, so it pushes the content the way the
     right sidebar does. It overlays only on mobile, where there is no room to push. */
  .nav-panel-container {
    flex-shrink: 0;
  }

  /* The shared resizer sits on the panel's right edge, not its left. */
  .nav-panel-resizer {
    left: auto;
    right: 0;
  }

  /* No scrim on desktop: the story stays visible and interactive beside the panel, so the
     reader can jump, look at where they landed, and jump again. */
  .nav-panel-scrim {
    display: none;
    position: absolute;
    inset: 0;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 44;
    border: none;
    cursor: pointer;
  }

  /* Right edge swipe zone */
  .swipe-edge-zone {
    position: fixed;
    right: 0;
    top: 0;
    width: 20px;
    height: 100%;
    z-index: 30;
  }

  .swipe-edge-zone-left {
    right: auto;
    left: 0;
  }

  /* Mobile styles */
  @media (max-width: 768px) {
    .mobile-sidebar-overlay {
      display: block;
      top: max(var(--safe-top), 28px);
    }

    .sidebar-container {
      position: fixed;
      right: 0;
      top: max(var(--safe-top), 28px);
      bottom: var(--safe-bottom);
      animation: slide-in 0.2s ease-out;
    }

    .swipe-edge-zone {
      width: 30px;
      top: max(var(--safe-top), 28px);
    }

    .nav-panel-scrim {
      display: block;
    }

    /* The panel overlays at a fixed width here, so there is nothing to drag. Tied to this
       query rather than a utility class, so it cannot disagree with the overlay breakpoint. */
    .nav-panel-resizer {
      display: none;
    }

    .nav-panel-container {
      position: absolute;
      left: 0;
      top: 0;
      bottom: 0;
      z-index: 45;
      /* Overrides the inline width the desktop resizer sets. */
      width: calc(100vw - 3rem) !important;
      max-width: 288px;
      animation: slide-in-left 0.2s ease-out;
    }
  }

  @keyframes slide-in {
    from {
      transform: translateX(100%);
    }
    to {
      transform: translateX(0);
    }
  }

  @keyframes slide-in-left {
    from {
      transform: translateX(-100%);
    }
    to {
      transform: translateX(0);
    }
  }
</style>
