name: Pre-release

on:
  push:
    tags:
      - 'v*-pre*' # v0.5.5-pre.1
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-desktop:
    uses: ./.github/workflows/build-desktop.yml
    with:
      prerelease: true
    secrets: inherit

  build-android:
    uses: ./.github/workflows/build-android.yml
    with:
      prerelease: true
    secrets: inherit
